routes/web.php
        Route::put("/update-tagihan/{id}", "BendaharaController@update")->name("bendahara.update");
        Route::delete("/delete-tagihan/{id}", "BendaharaController@delete")->name("bendahara.delete");
        Route::post("/store-tagihan", "BendaharaController@store")->name("bendahara.store");
        Route::get("/data", "BendaharaController@data")->name("bendahara.data");

        //transaksi-tagihan
        Route::get("/transaksi-tagihan", "TransaksiController@index")->name("transaksi.index");
        Route::post("/transaksi-tagihan/store", "TransaksiController@store")->name("transaksi.store");
        Route::post("/transaksi-tagihan/setor", "TransaksiController@setor")->name("transaksi.setor");

        //log transaksi
        Route::get("/list/log-transaksi-tagihan", "TransaksiController@list_log_transaksi")->name("transaksi.list");
        Route::get("/log-transaksi-tagihan/tarik-saldo/{id}", "TransaksiController@tarik_saldo")->name("transaksi.tarik");
        Route::get("/log-transaksi-tagihan", "TransaksiController@log_transaksi")->name("transaksi.logtrans");
        Route::get("/konfirmasi/{id}", "TransaksiController@konfirmasi")->name("transaksi.konfirmasi");
    }
);

// Data Jamiyyah/PW
Route::group(
    [
        "prefix" => "jamiyyah/pw",
        "middleware" => ["auth"],
    ],
    function () {
        Route::get("/", "PwController@index")->name("pimpinanWilayah.index");
        Route::get("/datatables", "PwController@dataTables")->name(
            "pimpinanWilayah.datatables"
        );
        Route::post("/store", "PwController@store")->name(
            "pimpinanWilayah.store"
        );
        Route::get("/get/{id}", "PwController@get")->name(
            "pimpinanWilayah.get"
        );
        Route::put("/update-data", "PwController@update")->name(
            "pimpinanWilayah.update"
        );
        Route::delete("/{id}/delete", "PwController@delete")->name(
            "pimpinanWilayah.delete"
        );
    }
);

// anggota mutasi
Route::group(
    ["prefix" => "mutasi", "middleware" => ["permission:mutasi.*", "auth"]],
    function () {
        Route::get("/", "AnggotaMutasiController@index")->name(
            "anggotaMutasi.index"
        );
        Route::get("/datatables", "AnggotaMutasiController@dataTables")->name(
            "anggotaMutasi.datatables"
        );
        Route::get("/get/{id}", "AnggotaMutasiController@get")->name(
            "anggotaMutasi.get"
        );
        // manipulate data
        Route::post("/store", "AnggotaMutasiController@store")->name(
            "anggotaMutasi.store"
        );
        Route::put("/{id}", "AnggotaMutasiController@update")->name(
            "anggotaMutasi.update"
        );
        Route::delete("/{id}/delete", "AnggotaMutasiController@delete")->name(
            "anggotaMutasi.delete"
        );
    }
);

Route::group(["prefix" => "register"], function () {
    Route::get("/", "Auth\RegisterController@index")->name("register.index");
    Route::post("/get", "Auth\RegisterController@get")->name("register.ceknpa");
    Route::get("/activation/{id}", "Auth\RegisterController@activation")->name(
        "register.activation"
    );
    // manipulate data
    Route::post("/create", "Auth\RegisterController@store")->name(
        "register.create"
    );
});

Route::group(["prefix" => "login"], function () {
    Route::get("/", "Auth\LoginController@index")->name("login.index");
    Route::post("/cek", "Auth\LoginController@cek_login")->name("login.cek");
});

Route::view("/setting/modul", "ana.modul.index");
Route::view("/setting/modul/{id}", "ana.menu.index");
Route::view("/account/role", "ana.role.index");

// Examples
Route::view("/examples/plugin-helper", "examples.plugin_helper");
Route::view("/examples/plugin-init", "examples.plugin_init");
Route::view("/examples/blank", "examples.blank");

// prototipe
//Route::view('/auth/login', 'auth.login');
Route::view("/email/activation", "email.activation");

Auth::routes();

Route::get("/provinces", "CountryController@provinces");
Route::get("/regencies", "CountryController@regencies");
Route::get("/districts", "CountryController@districts");
Route::get("/village", "CountryController@villages");

Route::group(
    ["prefix" => "laravel-filemanager", "middleware" => ["web", "auth"]],
    function () {
        Lfm::routes();
    }
);

Route::group(["prefix" => "/jamiyyah/monografi"], function () {
    Route::resource("pj", "MonografiPjController")->middleware([
        "auth",
        "permission:monografipj.*",
    ]);
    Route::resource("pc", "MonografiPcController")->middleware([
        "auth",
        "permission:monografipc.*",
    ]);
    Route::resource("pd", "MonografiPdController")->middleware([
        "auth",
        "permission:monografipd.*",
    ]);
    Route::resource("pw", "MonografiPwController")->middleware([
        "auth",
        "permission:monografipw.*",
    ]);
});

Route::group(
    ["prefix" => "/jamiyyah/performa", "as" => "performa."],
    function () {
        Route::resource("/pd", "PerformaPdController")->middleware([
            "auth",
            "permission:indexperformapd.*",
        ]);
        Route::resource("/pc", "PerformaPcController")->middleware([
            "auth",
            "permission:indexperformapc.*",
        ]);
        Route::resource("/pw", "PerformaPwController")->middleware([
            "auth",
            "permission:indexperformapw.*",
        ]);
        Route::resource("/pj", "PerformaPjController")->middleware([
            "auth",
            "permission:indexperformapj.*",
        ]);
    }
);

// Data PD
Route::group(["prefix" => "pd"], function () {
    Route::resource("pdaerah", "PDaerahController")->middleware([
        "auth"
    ]);
    Route::get("/datatables/pd/", "PDaerahController@datatables")->name(
        "pd.datatables"
    );
    Route::get("/get/{id}", "PDaerahController@get")->name("pd.get");
    // Route::put('/update', 'PDaerahController@update')->name('pd.updatedata'); //bentrok namanya dengan pd monografi
    Route::put("/update", "PDaerahController@update");
    Route::get("/get-pd-select2", "PDaerahController@getPcByName")->name("pd.select2");
    Route::delete("/{id}/delete", "PDaerahController@delete")->name(
        "pd.delete"
    );
});

//dropdown chain PW, PD, PC
Route::get("/get-pw", "PwController@getAllPwPublic");
Route::get("/get-pw-select2", "PwController@getPWByName");
Route::get("/get-related-pd/{pw}", "PwController@getRelatedPD");
Route::get("/get-related-pc/{pd}", "PDaerahController@getRelatedPC");

Route::post(
    "/reset-password-email-or-npa",
    "Auth\ForgotPasswordController@checkUserExist"
)->name("reset.password.email.npa");

Route::get(
    "/reset-password-anggota/{token}",
    "Auth\ForgotPasswordController@checkToken"
)->name("reset.password.token");

Route::post(
    "/reset-password-verification/{token}",
    "Auth\ForgotPasswordController@verifyUserAndPassword"
)->name("reset.password.verification");

Route::group(
    [
        "prefix" => "data-her-registrasi",
        "middleware" => ["permission:herregistrasi.*", "auth"],
    ],
    function () {
        Route::get("/datatables", "HerRegistrasiController@dataTables")->name(
            "herregistrasi.datatables"
        );
        Route::post(
            "/proses-approval",
            "HerRegistrasiController@prosesApproval"
        )->name("herregistrasi.proses_approval");
        Route::get("/", "HerRegistrasiController@indexTable")->name(
            "herregistrasi.index_table"
        );
        Route::post(
            "/set-status/{id}/{status}",
            "HerRegistrasiController@setStatus"
        )->name("herregistrasi.set_status");
    }
);

Route::group(
    [
        "prefix" => "data-registrasi",
        "middleware" => ["permission:rekapcaang.*", "auth"],
    ],
    function () {
        Route::get("/datatables", "RegistrasiController@dataTables")->name(
            "registrasi.datatables"
        );
        Route::post(
            "/proses-approval",
            "RegistrasiController@prosesApproval"
        )->name("registrasi.proses_approval");
        Route::get("/", "RegistrasiController@indexTable")->name(
            "registrasi.index_table"
        );
        Route::post(
            "/set-status/{id}/{status}",
            "RegistrasiController@setStatus"
        )->name("registrasi.set_status");
    }
);

Route::group(["prefix" => "caang"], function () {
    Route::get("/", "CaangAdminController@viewPublicForm");
});

Route::group(
    [
        "prefix" => "data-calon-anggota",
        "middleware" => ["permission:caang.*", "auth"],
    ],
    function () {
        Route::get("/", "CaangAdminController@index")->name("calon.caang.index");
        Route::post(
            "/mass-approve",
            "CaangAdminController@setApproveCaang"
        )->name("caang.mass_approve");
        Route::post(
            "/mass-approve-pc",
            "CaangAdminController@setApproveCaangLevelPC"
        )->name("caang.mass_approve_pc");
        Route::post(
            "/mass-approve-pd",
            "CaangAdminController@setApproveCaangLevelPD"
        )->name("caang.mass_approve_pd");
        Route::post(
            "/mass-approve-pw",
            "CaangAdminController@setApproveCaangLevelPW"
        )->name("caang.mass_approve_pw");
        Route::get("/datatables", "CaangAdminController@dataTables")->name(
            "caang.datatables"
        );
        Route::get("/{id}", "CaangAdminController@detail")->name(
            "caang.detail"
        );
        Route::delete("/{id}/delete", "CaangAdminController@delete")->name(
            "caang.delete"
        );
        Route::get("/{id}/edit", "CaangAdminController@edit")->name(
            "caang.show-edit"
        );
        Route::put("/update", "CaangAdminController@update")->name(
            "calon.caang.update"
        );
        Route::put(
            "/{id}/edit-foto",

app/Http/Controllers/MonografiController.php
<?php

namespace App\Http\Controllers;

use App\Model\Jamaah;
use App\Model\KejamiyyahanPj;
use App\Model\PC;
use App\Model\PD;
use App\Model\Province;
use App\Model\PW;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;

class MonografiController extends Controller
{
    public function showMonografiPJ()
    {
        $dataPJ = Jamaah::all();
        $dataPC = PC::all();
        $dataPD = PD::all();
        $dataPW = PW::all();
        $provinces = Province::all();
        return view('ana.monografi.pj.index', compact('dataPC', 'dataPD', 'dataPW', 'provinces', 'dataPJ'));
    }

    public function addMonografiPJ()
    {
        $dataPC = PC::all();
        $dataPD = PD::all();
        $dataPW = PW::all();
        $provinces = Province::all();
        return view('ana.monografi.pj.add', compact('dataPC', 'dataPD', 'dataPW', 'provinces'));
    }

    public function createMonografiPJ(Request $request)
    {
        $status = false;
        $validation = Validator::make($request->all(), [
            'kode_pj' => 'required',
            'nama_pj' => 'required|max:50',
            'no_pc' => 'required',
            'no_pd' => 'required',
            'no_pw' => 'required',
            'provinsi' => 'required',
            'kabupaten' => 'required',
            'kecamatan' => 'required',
            'desa' => 'required',
            'longitude' => 'nullable',
            'latitude' => 'nullable',
            'email' => 'required|max:50',
            'no_telpon' => 'required|max:15',
            'alamat' => 'required|max:100',
            'luas' => 'nullable',
            'bw_timur' => 'max:50',
            'bw_barat' => 'max:50',
            'bw_selatan' => 'max:50',
            'bw_utara' => 'max:50',
            'jarak_provinsi' => 'max:50',
            'jarak_kabupaten' => 'max:50',
            'ketua' => 'required',
            'sekretaris' => 'required',
            'bendahara' => 'required',
            'hari_ngantor' => 'required',
            'waktu_ngantor' => 'required',
            'musjam_terakhir_masehi' => 'required',
            'musjam_terakhir_hijriyyah' => 'required',
            'anggota_biasa' => 'required',
            'anggota_luar_biasa' => 'nullable',
            'mutasi_persis' => 'nullable',
            'mutasi_tempat' => 'nullable',
            'meninggal_dunia' => 'nullable',
            'tidak_herReg' => 'nullable',
            'mengundurkan_diri' => 'nullable',
            'calon_anggota' => 'nullable',
            'photo' => 'nullable|mimes:jpg,png,jpeg'
        ]);
        if ($validation->fails()) {
            return response()->json([
                'message' => $validation->errors()->getFormat(),
                'status' => $status
            ]);
        } else {
            try {
                DB::beginTransaction();

                $jamaah = new Jamaah();
                $jamaah->kode_pj = $request->Input('kode_pj');
                $jamaah->nama_pj = $request->Input('nama_pj');
                $jamaah->no_pc = $request->Input('no_pc');
                $jamaah->no_pd = $request->Input('no_pd');
                $jamaah->no_pw = $request->Input('no_pw');
                $jamaah->provinsi = $request->Input('provinsi');
                $jamaah->kabupaten = $request->Input('kabupaten');
                $jamaah->kecamatan = $request->Input('kecamatan');
                $jamaah->desa = $request->Input('desa');
                $jamaah->latitude = $request->Input('latitude');
                $jamaah->longitude = $request->Input('longitude');
                $jamaah->email = $request->Input('email');
                $jamaah->no_telpon = $request->Input('no_telpon');
                $jamaah->alamat = $request->Input('alamat');
                $jamaah->luas = $request->Input('luas');
                $jamaah->bw_utara = $request->Input('bw_utara');
                $jamaah->bw_selatan = $request->Input('bw_selatan');
                $jamaah->bw_timur = $request->Input('bw_timur');
                $jamaah->bw_barat = $request->Input('bw_barat');
                $jamaah->jarak_provinsi = $request->Input('jarak_provinsi');
                $jamaah->jarak_kabupaten = $request->Input('jarak_kabupaten');
                $jamaah->created_by = $request->Input('created_by');

                $status = $jamaah->save();

                $jamiyyahPj = new KejamiyyahanPj();
                $jamiyyahPj->kode_pj = $request->Input('kode_pj');
                $jamiyyahPj->nama_pj = $request->Input('nama_pj');
                $jamiyyahPj->no_pc = $request->Input('no_pc');
                $jamiyyahPj->no_pd = $request->Input('no_pd');
                $jamiyyahPj->no_pw = $request->Input('no_pw');
                $jamiyyahPj->provinsi = $request->Input('provinsi');
                $jamiyyahPj->kabupaten = $request->Input('kabupaten');
                $jamiyyahPj->kecamatan = $request->Input('kecamatan');
                $jamiyyahPj->desa = $request->Input('desa');
                $jamiyyahPj->ketua = $request->Input('ketua');
                $jamiyyahPj->sekretaris = $request->Input('sekretaris');
                $jamiyyahPj->bendahara = $request->Input('bendahara');
                $jamiyyahPj->hari_ngantor = $request->Input('hari_ngantor');
                $jamiyyahPj->waktu_ngantor = $request->Input('waktu_ngantor');
                $jamiyyahPj->musjam_terakhir_masehi = $request->Input('musjam_terakhir_masehi');
                $jamiyyahPj->musjam_terakhir_hijriyyah = $request->Input('musjam_terakhir_hijriyyah');
                $jamiyyahPj->anggota_biasa = $request->Input('anggota_biasa');
                $jamiyyahPj->anggota_luar_biasa = $request->Input('anggota_luar_biasa');
                $jamiyyahPj->tidak_herReg = $request->Input('tidak_herReg');
                $jamiyyahPj->mutasi_persis = $request->Input('mutasi_persis');
                $jamiyyahPj->mutasi_tempat = $request->Input('mutasi_tempat');
                $jamiyyahPj->mengundurkan_diri = $request->Input('mengundurkan_diri');
                $jamiyyahPj->meninggal_dunia = $request->Input('meninggal_dunia');
                $jamiyyahPj->calon_anggota = $request->Input('calon_anggota');
                $status = $jamiyyahPj->save();

                DB::commit();
            } catch (Throwable $e) {
                DB::rollBack();
            }

            Session::flash('message', 'Data Jamaah berhasil disimpan!');
            $dataPJ = Jamaah::all();
            $dataPC = PC::all();
            $dataPD = PD::all();
            $dataPW = PW::all();
            $provinces = Province::all();
            return view('ana.monografi.pj.index', compact('dataPC', 'dataPD', 'dataPW', 'provinces', 'dataPJ'));
        }
    }

    public function editMonografiPJ($id)
    {
        $dataPJ = Jamaah::find($id);
        $kejamiyyahanPj = KejamiyyahanPj::find($id);
        $dataPC = PC::all();
        $dataPD = PD::all();
        $dataPW = PW::all();
        $provinces = Province::all();

        return view('ana.monografi.pj.edit', compact('dataPC', 'dataPD', 'dataPW', 'provinces', 'dataPJ', 'kejamiyyahanPj'));
    }

//    public function updateMonografiPJ(Request $request, Jamaah $jamaah, KejamiyyahanPj $kejamiyyahanPj)
//    {
//
//        $dataPJ = Jamaah::all();
//        $kejamiyyahanPj = KejamiyyahanPj::all();
//        $dataPC = PC::all();
//        $dataPD = PD::all();
//        $dataPW = PW::all();
//        $provinces = Province::all();
//        return view('ana.monografi.pj.index', compact('dataPC', 'dataPD', 'dataPW', 'provinces', 'dataPJ', 'kejamiyyahanPj'));
//    }
}

resources/views/ana/monografi/pd/index.blade.php
@extends('layouts.backend')

@section('css_before')
    <!-- Page JS Plugins CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('js/plugins/datatables/dataTables.bootstrap4.css') }}">
    <link rel="stylesheet" href="{{ asset('js/plugins/datatables/buttons-bs4/buttons.bootstrap4.min.css') }}">

@endsection

@section('content')
    <!-- Hero -->
    {{-- <main id="main-container"> --}}
        <!-- Hero -->
        <div class="bg-body-light">
            <div class="content content-full">
                <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
                    <h1 class="flex-sm-fill h3 my-2">
                        Data Pimpinan Daerah <small
                            class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted">List</small>
                    </h1>
                    <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                        <ol class="breadcrumb breadcrumb-alt">
                            <li class="breadcrumb-item">Data Pimpinan Daerah</li>
                            <li class="breadcrumb-item" aria-current="page">
                                <a class="link-fx" href="/dashboard">Dashboard</a>
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <!-- END Hero -->

        <!-- Page Content -->
        <div class="content">
            <!-- Dynamic Table with Export Buttons -->
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Table <small>Data Pimpinan Daerah</small></h3>
                    @if(Permission::checkPermission('monografipd.create'))
                        <a href="{{route('pd.create')}}" class="btn btn-success btn-sm"><span
                                class="si si-plus"></span> Tambah</a>
                    @endif
                </div>
                <div class="block-content block-content-full">
                    <div class="table-responsive">
                        <table
                            class="table table-bordered table-striped table-vcenter js-dataTable-monografi-pd dataTable no-footer"
                            id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                            <thead>
                            <tr role="row">
                                <th>Photo</th>
                                <th>PD</th>
                                <th>PW</th>
                                <th>Email</th>
                                <th>Aksi</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($monografiPD as $pd)
                                <tr>
                                    <td class="font-w600 font-size-sm">
                                        @if($pd->foto != null && $pd->foto != "")
                                            <img width="70px"
                                                src="{{ Storage::disk('s3')->url('images/monografi/pd/'. $pd->foto) }}"
                                                alt="{{$pd->foto}}">
                                        @else
                                            <img width="70px" src="{{ asset('media/photos/desa.png') }}"
                                                alt="{{$pd->foto}}">
                                        @endif
                                    </td>
                                    <td class="font-w600 font-size-sm">{{$pd->nama_pd}}</td>
                                    <td class="font-w600 font-size-sm">{{$pd->pw->nama_pw}}</td>
                                    <td class="font-w600 font-size-sm">{{$pd->email}}</td>
                                    <td>
                                        <div class="btn-group float-right"></div>

                                        @if(Permission::checkPermission('monografipd.read'))
                                            <a href="{{ route('pd.show', $pd->id, false) }}"
                                            class="btn btn-primary btn-sm"><i class="si si-list"></i></a>
                                        @endif

                                        @if(Permission::checkPermission('monografipd.update'))
                                            <a href="{{ route('pd.edit', $pd->id, false) }}"
                                            class="btn btn-warning btn-sm"><i class="si si-pencil"></i></a>
                                        @endif

                                        @if(Permission::checkPermission('monografipd.delete'))
                                            <button type="button" class="btn btn-danger btn-sm"
                                                    onclick="remove('{{ route('pd.destroy', $pd->id, false) }}')">
                                                <i class="si si-trash"></i></button>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- END Page Content -->
    {{-- </main> --}}
    <!-- END Page Content -->


@endsection

@section('js_after')
    <!-- Page JS Plugins -->
    <script src="{{ asset('js/plugins/jquery-bootstrap-wizard/bs4/jquery.bootstrap.wizard.min.js') }}"></script>
    <script src="{{ asset('js/plugins/jquery-validation/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/buttons/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/buttons/buttons.print.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/buttons/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/buttons/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/buttons/buttons.colVis.min.js') }}"></script>


    <!-- Page JS Code -->
    <script>
        let dataTableUrl = "{{ url('/jamiyyah/datatables/pw')  }}";
        let pimpinan = "PW";

        jQuery('.js-dataTable-monografi-pd').dataTable({
            pageLength: 5,
            lengthMenu: [[5, 10, 15, 20], [5, 10, 15, 20]],
            order: [[0, 'asc']],
            autoWidth: true,
            buttons: [{
                extend: 'copy',
                className: 'btn btn-sm btn-primary'
            }, {
                extend: 'csv',
                className: 'btn btn-sm btn-primary'
            }, {
                extend: 'print',
                className: 'btn btn-sm btn-primary'
            }],
            dom: "<'row'<'col-sm-12'<'text-center bg-body-light py-2 mb-2'B>>>" + "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>><'row'<'col-sm-12'tr>><'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>"
        })

        function remove(route) {
            swal({
                title: "Apa anda yakin?",
                text: "Data akan dihapus dan tidak bisa dikembalikan!",
                type: "warning",
                showCancelButton: true,
                cancelButtonText: "Batal",
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Hapus!",
                closeOnConfirm: false
            }).then((result) => {
                if (result.value) {

                    swal({
                        title: 'Deleting data..',
                        allowOutsideClick: false,
                        allowEscapeKey: false,
                        allowEnterKey: false,
                        onOpen: () => {
                            swal.showLoading()
                        }
                    });

                    $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': $('[name="_token"]').val()
                        },
                        url: route,
                        type: 'DELETE',
                        dataType: 'json',
                        success: function (resp) {
                            if (resp == true) {
                                swal.close();
                                swal("Berhasil!", "Data telah berhasil dihapus.", "success").then((result) => {
                                    window.location.reload();
                                });
                            }
                        },
                        error: function (resp) {
                            swal.close();
                            alert(resp.responseJSON.message);
                        }
                    });
                }
            })
        }
    </script>
@endsection